# Nivell 1
## -Exercici 1:

Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu.

In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8],dtype='int64')
print(arr.ndim)
print(arr.shape)

1
(8,)


## -Exercici 2:
De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts.

In [5]:
average_value = (arr[0]+arr[1]+arr[2]+arr[3]+arr[4]+arr[5]+arr[6]+arr[7])/8
print(average_value)

4.5


## -Exercici 3:
Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.

In [16]:
arr2 = np.array([[1, 25, 7, 13, 9],[5, 8, 27, 4, 10],[2, 5, 6, 14, 7],[4, 5, 23, 12, 9],[9, 2, 16, 3, 11]])
max_value = np.max(arr2)
print('valor màxim array: ', max_value)
print('valor màxim eix 1: ',np.max(arr2[0]))
print('valor màxim eix 2: ',np.max(arr2[1]))
print('valor màxim eix 3: ',np.max(arr2[2]))
print('valor màxim eix 4: ',np.max(arr2[3]))
print('valor màxim eix 5: ',np.max(arr2[4]))

valor màxim array:  27
valor màxim eix 1:  25
valor màxim eix 2:  27
valor màxim eix 3:  14
valor màxim eix 4:  23
valor màxim eix 5:  16


# Nivell 2:
## -Exercici 4:
Mostreu-me amb exemples de diferents matrius, la regla fonamental de Broadcasting que diu : "les matrius es poden transmetre / broadcast si les seves dimensions coincideixen o si una de les matrius té una mida d'1".


In [22]:
a1 = np.array([1, 2, 3])
b1 = np.array([2, 4, 6])
print(a1 * b1)

a2 = np.array([1, 2, 3])
b2 = np.array([6])
print(a2 + b2)

a3 = np.array([[1, 25, 7, 13, 9],[5, 8, 27, 4, 10],[2, 5, 6, 14, 7]])
b3 = np.array([9, 2, 16, 3, 11])
print(a3 * b3)

a4 = np.array([[1, 25, 7, 13, 9],[5, 8, 27, 4, 10],[2, 5, 6, 14, 7]])
b4 = np.array([[4, 5, 23, 12, 9],[9, 2, 16, 3, 11],[12, 22, 17, 13, 9]])
print(a4 + b4)


[ 2  8 18]
[7 8 9]
[[  9  50 112  39  99]
 [ 45  16 432  12 110]
 [ 18  10  96  42  77]]
[[ 5 30 30 25 18]
 [14 10 43  7 21]
 [14 27 23 27 16]]


## - Exercici 5:
Utilitza la Indexació per extreure els valors d'una columna i una fila de la matriu. I suma els seus valors.

In [30]:
print(arr2[:,1]+arr2[1])

[30 16 32  9 12]


## -Exercici 6:
Mask la matriu anterior, realitzeu un càlcul booleà vectoritzat, agafant cada element i comprovant si es divideix uniformement per quatre.

Això retorna una matriu de mask de la mateixa forma amb els resultats elementals del càlcul.

In [56]:
mask = arr2 % 4 == 0
print(mask)

[[False False False False False]
 [False  True False  True False]
 [False False False False False]
 [ True False False  True False]
 [False False  True False False]]


## - Exercici 7:
A continuació, utilitzeu aquesta màscara per indexar a la matriu de números original. Això fa que la matriu perdi la seva forma original, reduint-la a una dimensió, però encara obteniu les dades que esteu cercant.